-- Script para verificar e criar tabelas faltantes no Supabase
-- Execute este script no SQL Editor do Supabase

-- =============================================
-- VERIFICAR TABELAS EXISTENTES
-- =============================================

SELECT 'Verificando tabelas existentes...' as status;

SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN (
  'filiais', 'cidades', 'medicos', 'clientes', 'usuarios',
  'agendamentos', 'datas_disponiveis', 'configuracoes_horarios',
  'tipos_fornecedores', 'fornecedores', 'titulos', 'ordens_servico', 
  'custos_os', 'movimentacoes_financeiras', 'templates_notificacoes', 
  'notificacoes_enviadas'
)
ORDER BY table_name;

-- =============================================
-- CRIAR TABELAS FALTANTES
-- =============================================

-- 1. Tabela datas_disponiveis
CREATE TABLE IF NOT EXISTS datas_disponiveis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidade_id BIGINT NOT NULL REFERENCES cidades(id),
  medico_id BIGINT NOT NULL REFERENCES medicos(id),
  data DATE NOT NULL,
  horarios_disponiveis JSONB NOT NULL DEFAULT '[]',
  ativa BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(cidade_id, medico_id, data)
);

-- 2. Tabela configuracoes_horarios
CREATE TABLE IF NOT EXISTS configuracoes_horarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidade_id BIGINT NOT NULL REFERENCES cidades(id) UNIQUE,
  horario_inicio TIME NOT NULL DEFAULT '08:00',
  horario_fim TIME NOT NULL DEFAULT '18:00',
  intervalo_minutos INTEGER NOT NULL DEFAULT 30,
  horarios_almoco JSONB DEFAULT '{"inicio": "12:00", "fim": "13:00"}',
  dias_funcionamento JSONB NOT NULL DEFAULT '[1,2,3,4,5]', -- 0=domingo, 1=segunda, etc
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabela tipos_fornecedores
CREATE TABLE IF NOT EXISTS tipos_fornecedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL UNIQUE,
  descricao TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabela fornecedores
CREATE TABLE IF NOT EXISTS fornecedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  cnpj VARCHAR(18) UNIQUE,
  cpf VARCHAR(14) UNIQUE,
  endereco TEXT,
  telefone VARCHAR(20),
  email VARCHAR(255),
  contato VARCHAR(255),
  tipo_id BIGINT REFERENCES tipos_fornecedores(id),
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT cnpj_or_cpf CHECK ((cnpj IS NOT NULL AND cpf IS NULL) OR (cnpj IS NULL AND cpf IS NOT NULL))
);

-- 5. Tabela titulos
CREATE TABLE IF NOT EXISTS titulos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero VARCHAR(50) NOT NULL UNIQUE,
  tipo VARCHAR(20) NOT NULL DEFAULT 'pagar',
  fornecedor_id BIGINT REFERENCES fornecedores(id),
  cliente_id BIGINT REFERENCES clientes(id),
  filial_id BIGINT NOT NULL REFERENCES filiais(id),
  categoria VARCHAR(255),
  descricao TEXT NOT NULL,
  valor DECIMAL(10, 2) NOT NULL,
  data_vencimento DATE NOT NULL,
  data_pagamento DATE,
  status VARCHAR(50) NOT NULL DEFAULT 'pendente',
  forma_pagamento VARCHAR(50),
  observacoes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT valid_tipo CHECK (tipo IN ('pagar', 'receber')),
  CONSTRAINT valid_status CHECK (status IN ('pendente', 'pago', 'vencido', 'cancelado'))
);

-- 6. Tabela ordens_servico
CREATE TABLE IF NOT EXISTS ordens_servico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero VARCHAR(50) NOT NULL UNIQUE,
  cliente_id BIGINT NOT NULL REFERENCES clientes(id),
  medico_id BIGINT REFERENCES medicos(id),
  filial_id BIGINT NOT NULL REFERENCES filiais(id),
  agendamento_id BIGINT REFERENCES agendamentos(id),
  data_os DATE NOT NULL,
  valor_venda DECIMAL(10, 2) NOT NULL DEFAULT 0,
  status VARCHAR(50) NOT NULL DEFAULT 'aberta',
  observacoes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT valid_status_os CHECK (status IN ('aberta', 'em_andamento', 'finalizada', 'cancelada'))
);

-- =============================================
-- CRIAR ÍNDICES PARA PERFORMANCE
-- =============================================

-- Índices para datas_disponiveis
CREATE INDEX IF NOT EXISTS idx_datas_disponiveis_cidade_id ON datas_disponiveis(cidade_id);
CREATE INDEX IF NOT EXISTS idx_datas_disponiveis_medico_id ON datas_disponiveis(medico_id);
CREATE INDEX IF NOT EXISTS idx_datas_disponiveis_data ON datas_disponiveis(data);
CREATE INDEX IF NOT EXISTS idx_datas_disponiveis_ativa ON datas_disponiveis(ativa);

-- Índices para configuracoes_horarios
CREATE INDEX IF NOT EXISTS idx_configuracoes_horarios_cidade_id ON configuracoes_horarios(cidade_id);

-- Índices para fornecedores
CREATE INDEX IF NOT EXISTS idx_fornecedores_nome ON fornecedores(nome);
CREATE INDEX IF NOT EXISTS idx_fornecedores_cnpj ON fornecedores(cnpj);
CREATE INDEX IF NOT EXISTS idx_fornecedores_cpf ON fornecedores(cpf);
CREATE INDEX IF NOT EXISTS idx_fornecedores_ativo ON fornecedores(ativo);

-- Índices para titulos
CREATE INDEX IF NOT EXISTS idx_titulos_numero ON titulos(numero);
CREATE INDEX IF NOT EXISTS idx_titulos_tipo ON titulos(tipo);
CREATE INDEX IF NOT EXISTS idx_titulos_data_vencimento ON titulos(data_vencimento);
CREATE INDEX IF NOT EXISTS idx_titulos_status ON titulos(status);

-- Índices para ordens_servico
CREATE INDEX IF NOT EXISTS idx_os_numero ON ordens_servico(numero);
CREATE INDEX IF NOT EXISTS idx_os_cliente_id ON ordens_servico(cliente_id);
CREATE INDEX IF NOT EXISTS idx_os_data_os ON ordens_servico(data_os);
CREATE INDEX IF NOT EXISTS idx_os_status ON ordens_servico(status);

-- =============================================
-- INSERIR DADOS INICIAIS
-- =============================================

-- Tipos de fornecedores básicos
INSERT INTO tipos_fornecedores (nome, descricao) VALUES
('Laboratório', 'Fornecedores de lentes e produtos ópticos'),
('Armações', 'Fornecedores de armações e óculos'),
('Equipamentos', 'Fornecedores de equipamentos médicos'),
('Serviços', 'Prestadores de serviços diversos'),
('Material de Escritório', 'Fornecedores de material de escritório')
ON CONFLICT (nome) DO NOTHING;

-- =============================================
-- VERIFICAÇÃO FINAL
-- =============================================

SELECT 'Tabelas criadas com sucesso!' as status;

SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN (
  'datas_disponiveis', 'configuracoes_horarios',
  'tipos_fornecedores', 'fornecedores', 'titulos', 'ordens_servico'
)
ORDER BY table_name;

SELECT 'Script executado com sucesso!' as resultado;