-- Script para corrigir o erro de foreign key constraint
-- Problema: tipos incompatíveis entre cidade_id (bigint) e id (uuid)

-- Primeiro, vamos verificar se a tabela configuracoes_horarios já existe
DROP TABLE IF EXISTS configuracoes_horarios CASCADE;

-- Recriar a tabela configuracoes_horarios com a constraint correta
CREATE TABLE configuracoes_horarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidade_id BIGINT NOT NULL REFERENCES cidades(id),
  horario_inicio TIME NOT NULL DEFAULT '08:00',
  horario_fim TIME NOT NULL DEFAULT '18:00',
  intervalo_minutos INTEGER NOT NULL DEFAULT 30,
  horarios_almoco JSONB DEFAULT '[]',
  dias_funcionamento JSONB NOT NULL DEFAULT '[1,2,3,4,5]', -- 0=domingo, 1=segunda, etc
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(cidade_id)
);

-- Adicionar o trigger para updated_at
CREATE TRIGGER set_timestamp_configuracoes_horarios 
  BEFORE UPDATE ON configuracoes_horarios 
  FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

-- Verificar se a correção funcionou
SELECT 'Tabela configuracoes_horarios corrigida com sucesso!' as status;

-- Verificar a estrutura da tabela para confirmar
SELECT 
  column_name, 
  data_type, 
  is_nullable,
  column_default
FROM information_schema.columns 
WHERE table_name = 'configuracoes_horarios' 
ORDER BY ordinal_position;